### ISSUE TITLE
Media player indicator gets misplaced, when ShutdownTimer is active

### ISSUE THREAD

**Issue by sojusnik** [neumann89/ShutdownTimer#22] opened 2016-01-25 23:46 UTC
As the title says, the [Media play indicator](https://extensions.gnome.org/extension/55/media-player-indicator/) gets misplaced, when the ShutdownTimer is installed and enabled, as shown here: [enabled](http://i.imgur.com/ORpb4zC.png) / [disabled](http://i.imgur.com/vRm1JDq.png).

Observed under Ubuntu Gnome 15.10 64-bit with Gnome 3.16.

Cheers!

**Comment by maweki** [comment] 2016-04-11 09:27
I think the issue is with the Media Player indicator.

https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/manager.js#L244-254

The function that positions the Media Player indicator is not very robust. In your case it just positions the player at the third from last position.

ShutdownTimer adds the seperator as a seperate item so that it takes up two slots, positioning the player right before it. For the builtin widgets, the seperator is part of the widget, positioning the player, again, third from last.

This should be fixed in the other widget with a more robust positioning function. So you might want to file this bug with Media play indicator with a reference to this issue.

**Comment by sojusnik** [comment] 2016-04-19 17:32
Thanks for the clarification! I'll open an according issue over there.

**Comment by neumann89** [comment] 2016-04-19 20:19
Thank you guys @maweki @maweki !

**Closed by neumann89** 2016-04-19 20:19 UTC
